import { wrapOpenAI } from '../src/wrappers/openai';

async function main(): Promise<void> {
  const mockOpenAI = {
    chat: {
      completions: {
        create: async (..._args: unknown[]) => ({
          id: 'chatcmpl_mock',
          model: 'gpt-4o-mini',
          choices: [
            {
              message: {
                role: 'assistant',
                content: 'This contract summary was generated by an AI model.'
              }
            }
          ]
        })
      }
    }
  };

  const wrapped = wrapOpenAI(mockOpenAI, {
    clientId: 'example_client',
    fetchImpl: async () => new Response('{}', { status: 200 })
  });

  const response: any = await wrapped.chat.completions.create({
    messages: [{ role: 'user', content: 'Summarize this contract.' }],
    model: 'gpt-4o-mini'
  });

  console.log('Output text:', response.choices[0].message.content);
  console.log('Compliance headers:', response._compliance_headers);
  console.log('JSON-LD block:', response._compliance);
  console.log('SHA-256 hash:', response._compliance_sha256);
}

void main();
