export interface ComplianceHeaders {
  'X-AI-Generated': 'true';
  'X-EU-AI-Act-Article': '50(2)';
  'X-ClauseKit-Verification-ID': string;
  'X-ClauseKit-Payload-Hash': string;
}

export function getComplianceHeaders(
  sha256Hash: string,
  verificationId: string
): ComplianceHeaders {
  return {
    'X-AI-Generated': 'true',
    'X-EU-AI-Act-Article': '50(2)',
    'X-ClauseKit-Verification-ID': verificationId,
    'X-ClauseKit-Payload-Hash': sha256Hash
  };
}

export function getJsonLdSchema(verificationId: string, timestamp: string) {
  return {
    '@context': 'https://schema.org',
    '@type': 'DigitalDocument',
    identifier: verificationId,
    dateCreated: timestamp,
    creditText: 'Generated by AI in accordance with EU AI Act Art. 50.',
    additionalProperty: [
      {
        '@type': 'PropertyValue',
        propertyID: 'digitalSourceType',
        value: 'https://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'
      },
      {
        '@type': 'PropertyValue',
        propertyID: 'euAiActArticle',
        value: '50(2)'
      }
    ]
  };
}
